kind: ConfigMap
apiVersion: v1
metadata:
  name: database-configmap
data:
  database_url: postgres://ms-database:5432
  database_user: postgres
  database_password: mypassword
  database_host: ms-database
  database_port: "5432"
