apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-database
  labels:
    app: ms-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-database
  template:
    metadata:
      labels:
        app: ms-database
    spec:
      containers:
      - name: ms-database
        image: postgres:15.5-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: database_password
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-persistent-storage
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: database-pvc
