apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-order
  labels:
    app: ms-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-order
  template:
    metadata:
      labels:
        app: ms-order
    spec:
      containers:
      - name: ms-order
        image: marcoschalet/order-service:v1.0.0
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: order-configmap
              key: database_url
        - name: NPM_RUN_COMMAND
          valueFrom:
            configMapKeyRef:
              name: order-configmap
              key: npm_run_command
        resources:
          limits:
            memory: "280Mi"
            cpu: "0.35"
          requests:
            memory: "180Mi"
            cpu: "0.2"
