kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-keycloak-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 300Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/psql/keycloak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-keycloak-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 300Mi
