apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: catalog
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcosChalet/infra-sisdis.git
    targetRevision: HEAD
    path: apps/catalog-service
  destination:
    server: https://kubernetes.default.svc
    namespace: catalog
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
