apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msg-broker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcosChalet/infra-sisdis.git
    targetRevision: develop
    path: apps/msg-broker
  destination:
    server: https://kubernetes.default.svc
    namespace: msg-broker
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
