kind: PersistentVolume
apiVersion: v1
metadata:
  name: database-catalog-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/data/psql/catalog"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-catalog-pvc
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
